### ISSUE TITLE
limf for cpomf

### ISSUE THREAD

**Issue by indrakaw** [nya/cpomf#11]
do it.

**Comment by RX14** [comment]
The api is compatible so it should work.

**Comment by clickbait** [comment]
ya, the whole idea is that cpomf _is_ pomf api compatible, so by extension any tools designed to work with pomf should work with cpomf.

If you're looking for something that's Nya.is exclusive, @Flat has a tool written in crystal [here](https://github.com/Flat/uploadtonya).

**Comment by indrakaw** [comment]
didn't even realise limf doesn't have token login ._.

**Comment by clickbait** [comment]
presumably because the token is unique to cpomf.
