### ISSUE TITLE
don't show download page when file doesn't exist

### ISSUE THREAD

**Issue by clickbait** [nya/cpomf#17]
which also leads to another problem, how should we delete files from the db if the antivirus deletes them?

**Comment by indrakaw** [comment]
can the antivirus tell that the files are deleted? or can nya/pomf tell that the files are deleted?

**Comment by RX14** [comment]
cdcd currently deletes the files in the directory (or it should...), we could make it callback to cpomf to handle the deletion entirely itself.

**Comment by clickbait** [comment]
@RX14 the latter is probably the better option, as deleting from the database should really be a thing
