### ISSUE TITLE
while requiring "crouter"

### ISSUE THREAD

**Issue by formatme** [nya/cpomf#19]
~/cpomf# crystal build --release pomf.cr
Error in pomf.cr:1: while requiring "./src/pomf"

require "./src/pomf"
^

in src/pomf.cr:1: while requiring "crouter": can't find file 'crouter' relative to '/root/cpomf/src'

require "crouter"
^

I don't understand this error shouldn't it be a dependency

**Comment by neko** [comment]
What Crystal version are you using?

Also, the installation instructions don't really mention it, but you need to run `shards install` in the root dir.

**Comment by neko** [comment]
Can I close this issue?

**Comment by neko** [comment]
rip. tag me if you need this reopened.

**Comment by formatme** [comment]
sorry, didn't see you responded. 
i will try setting up your site again soon.
