### ISSUE TITLE
shards install not grabbing md5

### ISSUE THREAD

**Issue by formatme** [nya/cpomf#25]
in lib/pg/src/pq/connection.cr:2: while requiring "crypto/md5": can't find file 'crypto/md5' relative to '/root/cpomf/lib/pg/src/pq'
require "crypto/md5"

the crypto/md5 is not under the lib folder compared to the rest of the things shards installed
running a new version of Crystal compared to Crystal 0.20.4

**Comment by formatme** [comment]
https://github.com/crystal-lang/crystal/tree/master/src/crypto

md5 is missing from the newest one so might be why

**Comment by neko** [comment]
we're currently running Crystal 0.20.4 without any issues; but we'll likely try to update to a newer Crystal version in the near future.

in the meantime i'd recommend just running Crystal 0.20.4, or submitting a pull request.

**Comment by formatme** [comment]
Switched to Crystal 0.20.4 and had to get shards and it compiles now
