### ISSUE TITLE
Time Outs

### ISSUE THREAD

**Issue by formatme** [nya/cpomf#27]
When going to the my site sometimes it does not load at all and gets a 504 gayway timeout
When it does work faq etc do not load. Maybe a PostgreSQL issue?
`upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxxx, server: share.alienz.win, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/`

https://share.alienz.win/

**Comment by formatme** [comment]
seems like it's not PostgreSQL
https://share.alienz.win/faq is a 504 Gateway Time-out

**Comment by formatme** [comment]
sometimes the site will load and sometimes it wont.

**Comment by formatme** [comment]
pretty sure has to due with nginx config

**Comment by formatme** [comment]
site stops working after i click on the logo or just refresh it a few times

**Comment by formatme** [comment]
upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxxx, server: share.alienz.win, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/

**Comment by formatme** [comment]
> 
server {
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 104.16.0.0/12;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 199.27.128.0/21;
set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2c0f:f248::/32;
set_real_ip_from 2a06:98c0::/29;
real_ip_header     CF-Connecting-IP;

    server_name share.alienz.win;
    access_log /var/log/nginx/share.alienz.win.access.log rt_cache; 
    error_log /var/log/nginx/share.alienz.win.error.log;

	listen 443 ssl;
	ssl on;
	ssl_certificate     /etc/letsencrypt/live/share.alienz.win/fullchain.pem;
	ssl_certificate_key     /etc/letsencrypt/live/share.alienz.win/privkey.pem;
       location / {
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
proxy_set_header X-NginX-Proxy true; 
proxy_set_header Host $http_host; 
proxy_set_header Upgrade $http_upgrade; 
proxy_set_header Connection "upgrade"; 
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_pass http://127.0.0.1:8081;
	client_max_body_size       10m;
	client_body_buffer_size    128k;

	proxy_connect_timeout      90s;
	proxy_send_timeout         90s;
	proxy_read_timeout 300;


	proxy_buffer_size          4k;
	proxy_buffers              4 32k;
	proxy_busy_buffers_size    64k;
	proxy_temp_file_write_size 64k;
       }

location /public {
  alias /home/formatme/cpomf/src/pomf/public;
}

}

**Comment by formatme** [comment]
location / {
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
       proxy_set_header X-NginX-Proxy true; 
       proxy_set_header Host $http_host; 
       proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection "upgrade"; 
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_pass http://127.0.0.1:8081;
	client_max_body_size       10m;
	client_body_buffer_size    128k;

	proxy_connect_timeout      90s;
	proxy_send_timeout         90s;
	proxy_read_timeout 300;


	proxy_buffer_size          4k;
	proxy_buffers              4 32k;
	proxy_busy_buffers_size    64k;
	proxy_temp_file_write_size 64k;
       }

**Comment by neko** [comment]
looks like the common PEBKAC error
