### ISSUE TITLE
still getting upstream timed out 

### ISSUE THREAD

**Issue by formatme** [nya/cpomf#28]
Maybe I'm retarded but I tried a lot of fixes and still cannot get the site to work without it timing out after a few refreshes. I thought it was because I was using http2 but that did not change anything.

**Comment by RX14** [comment]
Well I can't reproduce it so it's a configuration error you made. This issue tracker is not for general linux/nginx support. Please find someone else to help you.

**Comment by formatme** [comment]
Alright, ill look into it more.
