### ISSUE TITLE
Download non-whitlisted files via dl manager supports.

### ISSUE THREAD

**Issue by indrakaw** [nya/cpomf#29]
I just wondering the way I can download .zip, .rar, and .exe via uGet/Wget and FDM. I have to bypass CAPTCHA and it's IMPOSSIBLE. 

Here the idea: `"Cookie: allow-download=1"` 
That the way I able to download file directly via web browser, wget and download manager on Volafile.

I hope this feature implemented.

**Comment by clickbait** [comment]
the whole point of the captcha page is so that those files cannot be downloaded automatically; so that nya cannot be used to spread malware via a botnet

**Comment by indrakaw** [comment]
botnet can't run a wget command with args? :thinking:
